.TH SUPERUNPACK 1
.SH NAME
Superunpack \- Extract logical partitions from an super dynamic disk image
.SH SYNOPSIS
.B cd superimagedir && superunpack super.img
.SH DESCRIPTION
.PP
This experimental software allows you to extract logical partitions
from an super dynamic disk image.
.SH CAUTION
.PP
Superunpack was made for testing and educational purposes.  The author
is not responsible for what you do on/with your device using
Superunpack.  You must agree that you are using Superunpack on your own
risk.  The author is not responsible for anything else!
.SH USAGE
.TP
Step 1:
First you must extract superimage e.g. from an super.sin file (Sony firmare)
with an tool \- search xda for unpack any sony firmware \- or use another tool \- search xda for unsin
.TP
Step 2:
Run our superunpack tool from command line or if you are on Windows just drop
superimage onto superunpack.exe
.SH FEEDBACK
Don't forget to report your opinion, sucess, reports, logs, and so on.
Your suggestions are welcome!
.PP
.I https://forum.xda-developers.com/crossdevice-dev/sony/tool-superimage-dump-tool-t4120963
.PP
.I https://github.com/munjeni/super_image_dumper/issues
.SH AUTHOR
Mujeni
